### ISSUE TITLE
issue about Prepare HGMD-related data

### ISSUE THREAD

**Issue by zhangyuan5422** [LiuzLab/AI_MARRVEL#104]
I want to use AI-MAEEVEL to prioritize causal variants, but I cannot get the HGMD bgzip-compressed VCF file and HGMD Phenotype (hgmd_phenbase-*.dump.sql). Could you please give more details about how to do that? Thanks so much!
![image](https://github.com/user-attachments/assets/bbf5c6bd-bed5-4f9d-8ac4-30ab72e3c772)

**Comment by SpicyChicken6** [comment]
Hello @zhangyuan5422 , if you are trying to run AIM code directly with HGMD data included, you might want to contact [QIAGEN](https://digitalinsights.qiagen.com/products-overview/clinical-insights-portfolio/human-gene-mutation-database/) for purchasing the HGMD professional data license first, and they will provide the VCF and SQL data files needed here. We can't directly provide the HGMD data due to licensing issues. By default, the GitHub version of AIM run without HGMD data, at the cost of potentially lower accuracy.

However, you can also use our AIM web application at **ai.marrvel.org** to run your jobs by uploading your sample vcf and hpos, our AIM web application uses HGMD data for prediction so you don't need to purchase their data separately.
