### ISSUE TITLE
Error when running with hg38/GRCh38 samples

### ISSUE THREAD

**Issue by yaseminbridges** [LiuzLab/AI_MARRVEL#20]
**Describe the bug**
`FileNotFoundError` when running with hg38 sample. The application attempts to access a file under a GRCh38 subdirectory in the data dependencies, however, this does not exist as they are named hg38.

**Expected behavior**
The sample to run successfully without error of finding data dependency locations.
**Input data**

**Genome build**
hg38

**Screenshots or pipeline output**
```bash
Variable OMP_NUM_THREADS has been set to 1
INFO:    Using cached SIF image
VCF pre-processing
VCF quality filtering
Remove mitochondrial and unknown chromosome variants
Phrank scoring
join: /run/data_dependencies/phrank/hg19/gene_to_symbol_sorted.txt:16617: is not sorted: ENSG00000284015        MIR1281
Traceback (most recent call last):
  File "/run/phrank/src/run_phrank.py", line 33, in <module>
    if __name__ == "__main__": main(sys.argv[1], sys.argv[2])
  File "/run/phrank/src/run_phrank.py", line 27, in main
    p = Phrank(DAGFILE, DISEASEANNOTATIONS, DISEASEGENE, GENEANNOTATIONS)
  File "/usr/local/lib/python3.8/dist-packages/phrank/__init__.py", line 39, in __init__
    self._child_to_parent, self._parent_to_children = load_maps(dagfile)
  File "/usr/local/lib/python3.8/dist-packages/phrank/utils.py", line 3, in load_maps
    hpo_file = open(human_phenotype_map_file)
FileNotFoundError: [Errno 2] No such file or directory: '/run/data_dependencies/phrank/GRCh38/child_to_parent.txt'
Calculating phenotype similarities
```

**Comment by arine** [comment]
Hi @yaseminbridges ,

Thank you for providing the detailed information. It appears there is a mismatch in the genome build on the running command. When specifying the genome build, you should use `hg38` instead of `GRCh38`. Please ensure that your configuration aligns with our instructions, which you can find here: [Running with your sample](https://github.com/LiuzLab/AI_MARRVEL?tab=readme-ov-file#run-with-your-sample).

If the issue persists after making this adjustment, please let us know, and we'll investigate further.

Best regards,

AIM Team
